# version format
version: 2.0.{build}

# branches to build
branches:
  except:
    - gh-pages

# Operating system (build VM template)
os: Windows Server 2012

# scripts that are called at very beginning, before repo cloning
init:
#  - git config --global core.autocrlf input

# environment variables
environment:
  BASE_URL: https://api.postmarkapp.com
  READ_INBOUND_TEST_SERVER_TOKEN:
    secure: vJ62QJ+ipfs/ZBUGy2zjfQH9VhMO4bgSO6LgN0LqEaCMz/CYhDgElhxGOv3suNmt
  READ_SELENIUM_TEST_SERVER_TOKEN: 
    secure: ecc4V3tEuyfOAM6k+brMlDJN0Ec18mnLu6fMz5CmydmItoAdk2u3Xj8bEQYUXyPK
  READ_LINK_TRACKING_TEST_SERVER_TOKEN:
    secure: Iwzsp8yoHYe8nSZlWUYBLFwTMyEu9uo5wkt3GqZAGhTF4YVVW2Tg5cXZqxwgI/iH
  WRITE_ACCOUNT_TOKEN: 
    secure: 8WHfQJv+ZjUJp8pd5KcG0MjOelyEskSA9c/o0QnbIIQaV5hA3BqprE2cnorsCtnR
  WRITE_TEST_SERVER_TOKEN:
    secure: 4Pt2zMfFltMLSxpvud43AYFTlZWqXRurVBZgCajtzXk3hZpOV1wPPXvUPIUYcw1D
  WRITE_TEST_SENDER_EMAIL_ADDRESS:
    secure: Ke83sTbZc/+9/mokIvL8BxtPl6yA9tyjjs5kWTI06ZNodxd5gfXpm6Ns+6l0jMLZ
  WRITE_TEST_SENDER_SIGNATURE_PROTOTYPE:
    secure: dfbWIBndqE2MTj/qyJVP2I13XJlMKA64mI9/jcx1Fa1bZqPqW/tAfxeMViEMjQU836IYWflAG2h4IjARH+K+2uvhTz5y2rb9DzpLvzohKs8=
  WRITE_TEST_EMAIL_RECIPIENT_ADDRESS:
    secure: Ke83sTbZc/+9/mokIvL8BxtPl6yA9tyjjs5kWTI06ZNodxd5gfXpm6Ns+6l0jMLZ
  WRITE_TEST_DOMAIN_NAME:
    secure: +c0Z9XqvuliGsFGKWOLGEkeSx7dSTe41ehS8ZLpc/Bo=

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "2.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"


# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: true
  project_feed: true

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  project: src/PostmarkDotNet.sln  # path to Visual Studio solution or project
  publish_nuget: true              # package projects with .nuspec files and push to artifacts

  # MSBuild verbosity level
  # quiet|minimal|normal|detailed
  verbosity: normal

test:
  assemblies:
    - '**\*.Tests.dll'

after_test:
  - ps: .\poke-nuget-version.ps1
  - cmd: .\pack-nuget.bat

artifacts:
  # pushing all *.nupkg files in directory
  - path: '.\*.nupkg'

deploy:
  # Deploying to NuGet feed
  - provider: NuGet
    api_key:
      secure: sKvwxg5DmHjLtvBb0YEo9M+JYle83QWCDiGWfWOGOP6mQflp48qg1C5MJeNCw9cE
    skip_symbols: true
    on:
      appveyor_repo_tag: true
