#!/usr/bin/env bash
set -e
shopt -s expand_aliases

pushd "$(dirname $0)"

popd

pushd "$( dirname "$0" )/../src/"

nugetExe='../scripts/tools/nuget-cli/NuGet.CommandLine.4.3.0-preview3-4168/tools/NuGet.exe'

echo 'Run nuget restore...'
mono $nugetExe restore

msbuild /p:Configuration=Release /p:LibraryFrameworks='netstandard1.2'
dotnet test ./Postmark.Tests/Postmark.Tests.csproj /p:LibraryFrameworks='netstandard1.2'

# build for multi-target, now that we've built and tested on netstandard 1.2
mono $nugetExe restore
msbuild /t:Clean /p:Configuration=Release
msbuild /p:Configuration=Release


popd