#!/usr/bin/env bash
set -e
dir="$( dirname "$0" )/../src/"
pushd $dir
dotnet restore

msbuild /p:Configuration=Release /p:LibraryFrameworks='netstandard1.2'
dotnet test ./Postmark.Tests/Postmark.Tests.csproj /p:LibraryFrameworks='netstandard1.2'

echo 'Run nuget restore...'
nuget restore

echo 'Clean the project...'
msbuild /t:Clean /p:Configuration=Release

echo 'Build the solution'
msbuild /p:Configuration=Release

#Set a base path to locate ilrepack and the xunit runner.
DOTNET_TOOLS_BASE_DIR='$( dirname $0 )/tools'

popd