#!/usr/bin/env bash
set -e
shopt -s expand_aliases

pushd "$(dirname $0)"

popd

pushd "$( dirname "$0" )/../src/"

dotnet restore
dotnet test ./Postmark.Tests/Postmark.Tests.csproj /p:Configuration=Release /p:LibraryFrameworks='netstandard1.2'

popd